### ISSUE TITLE
sometimes it happens

### ISSUE THREAD

**Issue by zxdong262** [gustavohenke/bselect#19]
just look at the pic,  click the demo a few times, it may occur.

![issue](https://f.cloud.github.com/assets/1641949/407440/3d4febd6-aaf9-11e2-85f7-34801adb5ba2.png)

**Comment by gustavohenke** [comment]
Could you be more clear, please? Didn't understand/couldn't simulate.

**Comment by gustavohenke** [comment]
Forget it, I've looked again. Will fix it soon.

**Comment by gustavohenke** [comment]
Could you just tell me what browser is this?

**Comment by zxdong262** [comment]
in chrome 20+, just click and / or scroll, may happen, not every time

**Comment by gustavohenke** [comment]
Couldn't reproduce...

**Comment by gustavohenke** [comment]
Closing as it's been more then one month inactive.
