### ISSUE TITLE
Options with long titles overflow

### ISSUE THREAD

**Issue by derflocki** [gustavohenke/bselect#20]
The attached image show this, just adding 

```
.bselect-label {
    overflow: hidden
}
```

fixes the issue

![bselect-overflow](https://f.cloud.github.com/assets/758478/760680/3e91bd56-e7b4-11e2-8db9-13d0c49ad4ba.png)

**Comment by gustavohenke** [comment]
Thanks for the tip!
I'll apply the correction and release a new patch version the soon I'll be able to do so; that will happen in a few hours :)

**Comment by gustavohenke** [comment]
This fix is in the already released version 0.3.3.
