### ISSUE TITLE
change event is not triggered on the underlying DOM-Node

### ISSUE THREAD

**Issue by derflocki** [gustavohenke/bselect#23]
When changing the select, the value of the underlying DOM-Node is updated, however the `change`-event is not fired. So integrating other libraries, which monitor the select with `on('change')` is broken.

I'm currently experimenting with a fix patching the `select`-function however the way it is implemented I'm still having issues, and I'm not familiar enough with your code.

**Comment by gustavohenke** [comment]
The `select` method is right now searching by index; I need to make it work by value too.
About the `change` event, I'm fixing it now, just a wait a bit please :)

**Comment by gustavohenke** [comment]
This fix is in the latest version, 0.3.4.
